- hosts: all
  vars:
    ansible_user: "username"
    ansible_host: "{{ lookup('cred_d42', '{{inventory_hostname}}', 'host') }}"
    ansible_ssh_pass: "{{ lookup('cred_d42', '{{inventory_hostname}}', 'password', '{{ansible_user}}') }}"
    netports:
      port: "{{ item.port }}"
      port_speed: "{{ item.port_speed }}"
      hwaddress: "{{ item.hwaddress }}"
      primary_vlan_name: "{{ item.primary_vlan_name }}"
      port_type: "{{ item.port_type }}"
      remote_port: "{{ item.remote_port }}"
      remote_device_name: "{{ item.remote_device_name }}"
    with_items: "{{ lookup('cred_d42', '{{inventory_hostname}}', 'netports') }}"
  tasks:
    - shell: wget https://mirrors.kernel.org/ubuntu/pool/universe/c/check-mk/check-mk-agent_1.2.6p12-1_amd64.deb
    - shell: sudo apt install ./check-mk-agent_1.2.6p12-1_amd64.deb